Repository presidio-oss/factif-ai, pull requests merged in 2025-04, with the labels that each got.

#21 Explore mode stability improvements and bug fixes
  .changeset/tangy-trees-train.md
  CHANGELOG.md
  backend/src/controllers/chatController.ts
  backend/src/controllers/exploreController.ts
  backend/src/prompts/app-doc-generator.prompt.ts
  backend/src/prompts/explore-mode.prompt.ts
  backend/src/services/HistoryStorageService.ts
  backend/src/services/implementations/puppeteer/PuppeteerActions.ts
  backend/src/services/implementations/puppeteer/PuppeteerService.ts
  backend/src/services/llm/ExploreModeAnthropicProvider.ts
  backend/src/services/llm/ExploreModeOpenAIProvider.ts
  backend/src/utils/common.util.ts
  backend/src/utils/screenshotUtils.ts
  frontend/src/assets/factifai-logo.svg
  frontend/src/components/Chat/messages/Message.tsx
  frontend/src/components/ExploreMode/ExploreGraph.tsx
  frontend/src/components/ExploreMode/PageNode.tsx
  frontend/src/components/ExploreMode/RecentChats.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/hooks/useExploreChat.ts
  frontend/src/services/messageProcessor.ts
  frontend/src/services/routeClassifierService.ts
  frontend/src/types/message.types.ts
  frontend/src/utils/graph.util.ts
  package.json
Labels: good first issue

#23 Enhancements for Improved User Experience and Stability
  .changeset/mighty-cats-thank.md
  backend/src/prompts/explore-mode.prompt.ts
  backend/src/prompts/systemPrompts.prompt.ts
  backend/src/services/actionExecutorService.ts
  backend/src/services/implementations/docker/DockerActions.ts
  backend/src/services/implementations/puppeteer/PuppeteerActions.ts
  backend/src/services/implementations/puppeteer/PuppeteerService.ts
  backend/src/services/interfaces/BrowserService.ts
  frontend/src/App.css
  frontend/src/components/Chat/ChatInput.tsx
  frontend/src/components/Chat/messages/URLMessage.tsx
  frontend/src/components/Console/Console.tsx
  frontend/src/components/Preview/PreviewContent.tsx
  frontend/src/services/messageProcessor.ts
  frontend/src/services/uiInteractionService.ts
Labels: enhancement

#29 Fixes: Explore Mode
  .changeset/cuddly-queens-write.md
  backend/src/prompts/app-doc-generator.prompt.ts
  backend/src/prompts/explore-mode.prompt.ts
  backend/src/services/llm/ExploreModeAnthropicProvider.ts
  backend/src/services/llm/ExploreModeOpenAIProvider.ts
  backend/src/utils/costCalculator.ts
  frontend/src/hooks/useExploreChat.ts
Labels: bug, good first issue
